server:
  port: 8080
spring:
  oauth2:
    resource:
      userInfoUri: http://auth-server:9999/uaa/user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    datasource:
      platform: postgres
      url: jdbc:postgresql://postgres:5432/catalog
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: catalog

ribbon:
  eureka:
    enabled: true






